#pragma once

#define CONFIG_LV_PREDEFINED_DISPLAY_NONE 1//enable
#define CONFIG_LV_TFT_DISPLAY_CONTROLLER_ST7796S 1//enable

#define CONFIG_LV_HOR_RES_MAX 480
#define CONFIG_LV_VER_RES_MAX 320

#define CONFIG_LV_COLOR_DEPTH_16 1//enable
#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_LV_COLOR_16_SWAP 1//enable

#define CONFIG_LV_TFT_DISPLAY_PROTOCOL_SPI 1//enable

#define CONFIG_DISPLAY_ORIENTATION_LANDSCAPE 1//enable

#define CONFIG_LV_DISPLAY_ORIENTATION 2
#define CONFIG_LV_PREDEFINED_PINS_NONE 1//enable

#define CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ST7796S 1//enable

#define CONFIG_LV_TFT_DISPLAY_SPI_HSPI 1//enable

#define CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_SIO 1//enable


#define CONFIG_LV_TFT_DISPLAY_SPI_HALF_DUPLEX 1//enable

#define CONFIG_LV_TFT_CUSTOM_SPI_CLK_DIVIDER 2

//pin

#define CONFIG_LV_DISP_SPI_MOSI 13
#define CONFIG_LV_DISP_SPI_CLK 14
#define CONFIG_LV_DISPLAY_USE_SPI_CS 1//enable

#define CONFIG_LV_DISP_SPI_CS 15
#define CONFIG_LV_DISPLAY_USE_DC 1//enable

#define CONFIG_LV_DISP_PIN_DC 21
#define CONFIG_LV_DISP_PIN_RST 22
#define CONFIG_LV_DISP_PIN_BUSY 35

#define CONFIG_LV_ENABLE_BACKLIGHT_CONTROL 1//enable
#define CONFIG_LV_BACKLIGHT_ACTIVE_LVL 1//enable

#define CONFIG_LV_DISP_PIN_BCKL 23
#define CONFIG_LV_DISP_PIN_SDA 5
#define CONFIG_LV_DISP_PIN_SCL 4

#define CONFIG_LV_TOUCH_CONTROLLER 2

//touch pad init
#define CONFIG_LV_TOUCH_CONTROLLER_FT6X06 1//enable

#define CONFIG_LV_TOUCH_DRIVER_PROTOCOL_I2C 1//enable

#define CONFIG_LV_TOUCH_I2C_PORT_0 1//enable

#define CONFIG_LV_TOUCH_I2C_SDA 18
#define CONFIG_LV_TOUCH_I2C_SCL 19

#define CONFIG_LV_FT6X36_SWAPXY 1//enable

#define CONFIG_LV_FT6X36_INVERT_Y 1//enable


//---------------

#define LV_LVGL_H_INCLUDE_SIMPLE 1//enable

